### ISSUE TITLE
Improve APT repositories usability

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server-release#11]
Installing from apt repository is the most convenient way to get rabbit on deb-based OS, as you don't have to mess with dependencies yourself. But currently there are several issues that make APT repositories not that useful.

1. Official repository contains only the latest version, and this makes it unusable when you want reproducible installations (e.g.  https://github.com/puppetlabs/puppetlabs-rabbitmq uses this repo by default, but you can't pin specific version as it'll become unavailable soon).

2. packagecloud repos are a bit inconsistent, e.g. 3.6.6 is missing from `jessie`  dist

I think that the best thing would be to make all package versions available through official apt repository. If this is not feasible, making every github release an apt repository (by adding `Pacakges.gz` there) is also an option - this way there will be a way to use pinned version but still enjoy apt dependency resolution (actually, making every github release an apt repo may be an useful thing on itself, because it'll allow convenient installation of milestone releases).

**Comment by michaelklishin** [comment]
Package Cloud and Bintray have multiple versions and that's the short term solution we arrived at. Since our Debian packages are largely distribution-neutral, automation of PC package releases is a matter of moving all release parts to Concourse (probably a few months away) and adding a step that publishes to PC.

I'm happy to push `3.6.6` for Jessie or other missing distribution.

**Comment by michaelklishin** [comment]
OK, the `debian/wheezy` and `debian/jessie` "versions" of the 3.6.6 package are up on Package Cloud now.

**Comment by binarin** [comment]
Thanks. And what about making every github release also an apt repo by adding `Packages.gz` generated from the directory that contains the released .deb itself?

    dpkg-scanpackages . | gzip > Packages.gz

**Comment by michaelklishin** [comment]
@binarin we can do that if you say there's value in it. Once we move everything related to release production to [Concourse](https://ci.rabbitmq.com/), releasing to 3 or 4 Debian "repositories" is not going to be meaningfully different.

The faith of the rabbitmq.com apt repo long term is tricky because hosting multiple package versions is far from being an completely solved and obvious problem unless you are Package Cloud or Bintray ;) There are different toolchains each with its own drawbacks. But we recognize that the vast majority of Debian package users consume it from rabbitmq.com, so that repo will almost certainly stick around even though it goes against the things we'd like to do with the site (e.g. host it on Pivotal Web Services and Cloud Flare, like we already do for next.rabbitmq.com and previous.rabbitmq.com). Maintaining an entire
release archive on rabbitmq.com doesn't seem necessary to me, given that Package Cloud and/or Bintray have everything.

We've moved our release archive (rabbitmq.com/releases) [to Bintray](https://bintray.com/rabbitmq/archive) some 6 or so months ago when we did some initial work around moving the site and release artifacts to "teh Cloud."

Now just about every other change depends on moving 99% of the release toolchain to Concourse, from nightlies to milestones to final releases. This is fairly tricky to do when you have Windows and MacOS build machines involved (but Pivotal has teams that have done that before, so we are not entirely in an uncharted territory) and I expect it to take 2 to 3 months.

**Comment by michaelklishin** [comment]
Since we haven't posted much about it publicly, our goals with rabbitmq.com and release artifacts probably need some clarification. They are fairly obvious:

 * Redundancy across distribution sites (so that if the Russian govt decides to ban GitHub again or Package Cloud DNS server goes down, there's still at least functional "mirror")
 * Redundancy and ~ 0 time spent on operations from our team for rabbitmq.com (the doc sites)
 * Redundancy for our own distribution site (the apt repo, which has 10 years of baggage)
 * Use CDNs for more efficient last mile delivery

A lot of this can be achieved by moving as much as possible to Bintray, GitHub, Package Cloud. Our apt repo and release archive are the main sticking points: we cannot get rid of the former, which means we have to maintain our own infrastructure. We have to proxy rabbitmq.com/releases and discourage its use over external services. We have to move Community Plugins somewhere (historically they've been hosted on rabbitmq.com). We have to entirely separate them from documentation sites (which are static HTML and should be hosted on Pivotal Web Services with a CDN).

So that will take a few months, even though we already do some of the above:

 * Release to GitHub, Bintray, Package Cloud
 * All release notes are hosted on Github
 * Release archive is already on Bintray
 * Java, .NET and recently Erlang client are distributed via Maven repos, NuGet and Hex.pm. The former two are entirely decoupled from RabbitMQ releases (except for the 3.6.x series).
 * next.rabbitmq.com and previous.rabbitmq.com already run on PWS with Cloud Flare
 * Package verification against some 7-8 distributions is already done by Concourse
 * .NET client 4.x+ releases are done entirely on Concourse
 * Java client 4.x+ releases will very soon be done entirely on Concourse

I hope you get the idea: this involves way more than the apt repo because rabbitmq.com historically has had multiple separate parts hosted together :(

**Comment by dumbbell** [comment]
I believe this issue is resolved now:
* Bintray and packagecloud.io repositories are consistent regarding the distributions indexed.
* Multiple versions of RabbitMQ are available and there are even per-RabbitMQ-branch components on Bintray for people willing to stay with a particular minor release.

Please re-open if our Debian repositories are still a problem.
