### ISSUE TITLE
Can't set RABBITMQ_LOG_BASE via environment variable

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server-release#131]
Introduced by this commit: https://github.com/rabbitmq/rabbitmq-server-release/commit/4b7048205d1afa80bb0d644acb90e13106b2b8c1

Reported on the mailing list here: https://groups.google.com/d/topic/rabbitmq-users/bUaBxBzln6M/discussion

Workaround:

Create the file `/etc/rabbitmq/rabbitmq-env.conf` with the following contents:

```
LOG_BASE=/my/rabbitmq/log-base
```

**Comment by dumbbell** [comment]
Thank for the report!

Indeed, unlike the SysV init scripts, `rabbitmq-script-wrapper` gives no way to override the hard-coded `$RABBITMQ_LOG_BASE`.

Setting the variable in `rabbitmq-env.conf` will help for files created by RabbitMQ, but not for the files created by `rabbitmq-script-wrapper` (in the specific case of the Debian package, it redirects the output of the real rabbitmq-server(8) to files stored in `$RABBITMQ_LOG_BASE`).

Let's rewind a bit:

* The SysV init scripts in the Debian and RPM packages run `/usr/sbin/rabbitmq-server` (i.e. `rabbitmq-script-wrapper`) and redirect its stdout & stderr to files in `$RABBITMQ_LOG_BASE`.
* `rabbitmq-script-wrapper` in the Debian package already redirects stdout & stderr of the real rabbitmq-server(8) to the same files in `$RABBITMQ_LOG_BASE`.
* `rabbitmq-script-wrapper` in the RPM package does not mess with output redirection.

First, output redirection is set twice in the case of the Debian package (the one in the SysV init script being useless, because `/usr/sbin/rabbitmq-server` is already redirected). I'm wondering if users want to run `/usr/sbin/rabbitmq-server` directly and expect its output to be redirected to `/var/log/rabbitmq/startup_*`.

I will do some tests, but I feel we should get rid of the redirection in `rabbitmq-script-wrapper` (the Debian and RPM packages would behave the same). This would also solve the original reporter's problem (he is using the RPM package, so there is no redirection in `rabbitmq-script-wrapper`).

Second point: we use the variable `$RABBITMQ_LOG_BASE` to redirect output and it makes people think this can be configured. To me, the redirection is part of the packaging, not RabbitMQ itself. The directory is created and its ownership is set by the package. Furthermore, if people configure the log location in the RabbitMQ configuration file, this won't affect the output redirection.

Therefore, I think we should just rename that variable in the SysV init scripts (and in `rabbitmq-script-wrapper` if we don't implement my first suggestion) to something specific/local to those scripts, to eliminate the confusion.

What do you think?

**Comment by dumbbell** [comment]
In fact no, the SysV init script in the Debian package only redirects the output when stopping the server, not when starting it. Thus the redirection in `rabbitmq-script-wrapper` is used.

I will study why there is this difference between both packages.

**Comment by dumbbell** [comment]
I made two patches to address the two parts of my comment.

About the missing redirection in Debian's SysV init script, I found a solution I still need to further test. If everything works, then Debian & RPM packages/SysV init scripts would work the same.

**Comment by lukebakken** [comment]
This particular user wants to set `RABBITMQ_LOG_BASE` and then run `/usr/sbin/rabbitmq-server`. They aren't using `systemd` or `init`.

**Comment by dumbbell** [comment]
Yes, that's why I think we should just get rid of console redirection in `rabbitmq-script-wrapper` (which is copied to `/usr/sbin/rabbitmq-server` in the packages).
