### ISSUE TITLE
rabbitmq_v3_6_13_milestone1 - erlang.mk build not finding 'rabbit' dependency

### ISSUE THREAD

**Issue by ghost** [rabbitmq/rabbitmq-server-release#55]
I killed the build after a couple of these messages,  not finding a repository called 'rabbit' seemed like it could be an issue:

```
administrators-MacBook-Pro% git checkout -b rabbitmq_v3_6_13_milestone1
Switched to a new branch 'rabbitmq_v3_6_13_milestone1'
administrators-MacBook-Pro% 
administrators-MacBook-Pro% make clean                                 
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
 GEN    coverdata-clean
 GEN    clean-dist
 GEN    clean-source-dist
administrators-MacBook-Pro% make packages
erlang.mk:26: Please upgrade to GNU Make 4 or later: https://erlang.mk/guide/installation.html
 DEP    rabbit
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
^Cmake: *** [/bhesl/rabbitmq-server-release/deps/rabbit] Interrupt: 2
```

**Comment by lukebakken** [comment]
Hi Bryan - this is most likely due to a transient network issue. I'm building some generic unix packages right now in a Ubuntu 16 VM and it's working fine.

You can run `make V=2 packages` to see more information. If you continue to have issues, please post a message to [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) and we can continue there - we try to keep GH issues limited to actionable features and bugs only.

Finally ... you may want to install a newer GNU make using homebrew. I did that on my OS X laptop and have just aliased `gmake` as `make`.

Thanks!

**Comment by michaelklishin** [comment]
Please clone [the entire umbrella](https://github.com/rabbitmq/rabbitmq-public-umbrella) in order to produce a release.

For plugins we try to make them "buildable" as standalone repositories but this repo is not really a typical project (a plugin).

In case you want to build 3.6.13.M1 packages, you probably can use a [recent snapshot](http://www.rabbitmq.com/snapshots.html) instead. We have 3.6.13 M1 packages as well, I will upload them in a bit.

**Comment by ghost** [comment]
Thanks @michaelklishin + @lukebakken ! And correct. It was intermittent network fail.
