### ISSUE TITLE
Debian dependencies for rabbitmq-server 3.6.* do not cap max supported Erlang version

### ISSUE THREAD

**Issue by func0der** [rabbitmq/rabbitmq-server-release#83]
Hey guys,

I hope I have the right repository for this issue.
There already has been an issue for this over in the rabbitmq-server repository (https://github.com/rabbitmq/rabbitmq-server/issues/1668), but since someone mentioned there, that this is the place to go, I am here now.

This guide here explains that rabbitmq 3.6.15 and 3.6.16 are both only compatible with erland 19.3.x up to 20.3.x.

When I have a look at this [Packages](https://dl.bintray.com/rabbitmq/debian/dists/jessie/rabbitmq-server-v3.6.x/binary-amd64/Packages) file in the bintray debian repository it tells me that I need `erlang-nox (>= 1:16.b.3) | esl-erlang (>= 1:16.b.3)`.

This obviously COULD install the 19.3.x or 20.3.x version of erlang, but not right now as there is already the 21 version of erlang in the repository.

*Those versions should be bumped up to the requried 19.3.x and maxed out at 20.3.x, so that this package would become usable again.*

We have the same issue with the 3.7.7 version of rabbitmq-server: 

```
Depends: ..., erlang-nox (>= 1:19.3) | esl-erlang (>= 1:19.3), ...
```

*The erlang version should be `19.3.6.4` or higher.*

I do not another way to find a maintainer for that repository, so I would be nice, if you pointed me in the right direction in case this is the wrong place.

Thank you :)

**Comment by michaelklishin** [comment]
They are still compatible with R16B03 but we want to strongly discourage the use of anything older than `19.3.6.4` because of know bugs, lack of features and so on. I'm pretty sure our `3.6.x` (which has been EOL'ed in May) pipeline still runs a lot of tests on R16B03-1 as well as other versions.

**Comment by michaelklishin** [comment]
I will leave it to @dumbbell to decide. There are no future `3.6.x` releases planned. Our docs have a dedicated section for [package version pinning](http://www.rabbitmq.com/install-debian.html#apt-pinning) specifically for Erlang.

While it would be nice to cap the maximum version, producing a new release of an unsupported version just for that sounds like a pretty weird thing to do.

I'd recommend [upgrading](http://www.rabbitmq.com/upgrade.html) over trying to convince our team that we have to spend any more cycles on `3.6.x`.

**Comment by func0der** [comment]
> They are still compatible with R16B03...

You say that, but your [documentation](https://www.rabbitmq.com/which-erlang.html) says otherwise. I am confused therefore.
If the table in your docs does not state the requirements used in the repository, one of them is useless.

> While it would be nice to cap the maximum version, producing a new release of an unsupported version just for that sounds like a pretty weird thing to do.

I am not familiar with debian repositories regarding releases, but like this you are shipping out a broken combination of software hindering people to properly use it and have a bad first experience, if they are tied to 3.6.x for whatever reaseon (for example coming from debians official repository and trying to be save for the first couple of days).
Would you really need to create a whole new release for it, or would it just be enough to re-create the deb file?
As far as I have seen, apt should update the package if it find changed `Depends` headers, even if the version would be the same. I am not 100% sure about this though.

No matter what you do with 3.6, this is also broken in the newest 3.7 version as stated:

> We have the same issue with the 3.7.7 version of rabbitmq-server:
> Depends: ..., erlang-nox (>= 1:19.3) | esl-erlang (>= 1:19.3), ...
> The erlang version should be 19.3.6.4 or higher.

**Comment by michaelklishin** [comment]
@func0der I explained that we list `19.3.6.4` as the minimum supported version because we strongly want to discourage the use of any earlier versions. We don't want to break existing upgrades so we retained R16B03 compatibility even though it took a lot of effort to support 5 Erlang release series in RabbitMQ 3.6.x.

Erlang/OTP 21 was released after RabbitMQ 3.6.x went out of support. You decide whether that's a "broken combination".

Republishing of packages is not always possible (depending on the service) and not always encouraged. Packages can be versioned independently of software in this case (an apt feature), which is why this issue is not closed but under a consideration.

**Comment by michaelklishin** [comment]
@func0der you seem to be missing the point. Try running 3.6.16 on R16B03 and 3.7.7 on 19.3.0 and compare this with what the dependency requirements are in the package. The fact that those versions do not immediately error out on node start doesn't mean they are optimal or recommended out of the 5 supported Erlang release series for 3.6.x and 3 supported series for 3.7.x.

I don't have much to add. The docs try to steer the user to do the right thing without breaking those who already are on R16B03 (or 19.3) and would prefer not to see unexpected `apt-get upgrade` failures and potentially unexpected and complicated upgrades. If you believe that's broken then please make your case on the mailing list since this is not a discussion forum.

**Comment by michaelklishin** [comment]
[The pull request](https://github.com/rabbitmq/rabbitmq-website/pull/552) which switched the version documented as required to `19.3.6.4` explains the thinking.

**Comment by michaelklishin** [comment]
Per discussion with @dumbbell: the plan currently is to publish a new epoch (a revision in Debian terms) of the 3.6.16 package that does cap the maximum supported version. That should not affect any existing installations.

**Comment by michaelklishin** [comment]
We are close to be done with this, this pulled in several other dependency-related changes, e.g. we no longer can depend on metapackages such as `erlang-nox` since they don't pin their dependencies.

https://github.com/rabbitmq/rabbitmq-server-release/commit/f12ddea4e22c1579d9a18264bcf4405ebe6f65aa is one example or where this is headed.

**Comment by dumbbell** [comment]
After much work to adapt our CI pipeline, the Debian package of RabbitMQ 3.6.16-2 was finally published. It marks RabbitMQ 3.6.16 as incompatible with Erlang 21.x.

The pipeline is currently running to do the same with the RPM package. I will test it tomorrow and let the pipeline publish it.

**Comment by dumbbell** [comment]
I had to do a small bugfix to our Erlang RPM package, and now the version requirement range in RabbitMQ 3.6.16-2 is honored.

Therefore, all Debian and RPM packages of RabbitMQ 3.6.16 (3.6.16-2) will refuse to install with Erlang 21.x.
